### ISSUE TITLE
Reload viewer

### ISSUE THREAD

**Issue by zahranoorcs** [cuberis/openseadragon-curtain-sync#4]
Hi,
Is there a way to reload viewer in curtain Sync example? I am trying to change images in curtain and sync mode depending on dropdown values and the images change when the dropdown option changes. In openseadragon, I have done this using: 
**viewer1.close();
             viewer1.open({
             type: 'zoomifytileservice',
                   width: 3008,
                   height: 2000,
                   tilesUrl: "ZoomifyImageExample/"
            });**

But I am unable to do this in curtain Sync example. 
Can you please help me out?

**Comment by iangilman** [comment]
The Curtain/Sync viewer isn't set up to support opening a different set of images. I believe the assumption was you would have one page per set of images.

It probably wouldn't be terribly hard to update the code to support this, if you wanted to. I can see two scenarios:

1. Add a `destroy` function to `CurtainSyncViewer` so you can destroy the current viewer and create a new one with different images. That function might be as simple as:

```
    // ----------
    destroy: function () {
      if (this.mode) {
        this.mode.destroy();
      }
    },
```

2. You could add a `setImages` function to `CurtainSyncViewer` and move the image set up code from the constructor into it, along with forcing a `setMode` (I say forcing, since it first checks to see if you're asking for a new mode and doesn't bother changing if you're not, but in this case you need to do it anyway because the images are new).

Both of these options require changes to the code, but I think they are relatively self-contained. If you're up for making the change, it would be lovely if you could make a pull request out of it to share with everyone! Either way, let me know if you have questions :-)

**Comment by zahranoorcs** [comment]
Ian,

Thanks a lot for your help. 
I am trying to doing what u said. Is there a way I can simply update the tilesource instead of destroying the modes and setting the images again? Or if it is possible to destroy the viewer and reload with new images? 

I really appreciate your help.

Thanks,
Zahra

**Comment by zahranoorcs** [comment]
Ian,
Thanks a lot for your help!

I tried adding the destroy function in  window.CurtainSyncViewer = function (args) { 
but I got error. So, I added it in the following instead: 
 window.CurtainSyncViewer.prototype = OpenSeadragon.extend({
I think its working fine because after calling it, the screen is blank but I can still the viewer in the console. Am I doing it right? 
Also, can you help me with the second part? I didn't understand it well. 
I greatly appreciate your help. 
Thanks,
Zahra

**Comment by zahranoorcs** [comment]
Ian,

Can I share some code with you? I am stuck in changing images based on
dropdown.  The second part you told me is not working out.

I appreciate your help.

Thanks,
Zahra

**Comment by iangilman** [comment]
Sounds like you added `destroy` currently!

The second part was an alternate suggestion, so if you already have something that works you don't need to also do that. Of course if you'd prefer to do that instead of the destroy method, I can help answer your questions.

**Comment by zahranoorcs** [comment]
Ian,
The first solution worked like a charm. Thank you so much for your help. 
I will soon share the code. 

Thanks again :)

**Comment by zahranoorcs** [comment]
Ian,

I have another question! When I load the viewer with new images, every time the mode is reset to curtain mode. How can I contain the mode ?

**Comment by iangilman** [comment]
Before you destroy the old viewer, get the current mode like so:

```
var mode = viewer.getMode();
```

Then, when you create the new viewer, include this in the configuration:

```
  mode: mode,
```

It looks like `getMode` is documented at https://github.com/cuberis/openseadragon-curtain-sync, but the `mode` configuration option is not. If you're planning on doing a pull request for the new `destroy` function, you might want to add a mention in the documentation for the configuration option (as well as mentioning the destroyed function itself).

**Comment by zahranoorcs** [comment]
Ian,

Thanks a lot for all ur help and support. It worked!
I will mention the configuration option as well. 
Thanks

**Comment by zahranoorcs** [comment]
Ian,

I have 2 more questions! 

1. I have enabled the viewport navigator in curtain Sync and it seems that in Sync mode, the navigator size in both images is different. I can also share the screenshot with you. Is it possible to fix it? 

2. I am trying to enable navigation control toolbar in Curtain sync as I am not using the separate Zoom buttons. But the toolbar is not showing up. I am using the following code: 

  ```
viewer = new CurtainSyncViewer({
          container: document.querySelector('#viewer'),
           mode: mode,
          images: [
            {
              key: 'vis',
              tileSource:img1,
             
              shown: true
            },
            {
              key: 'xra',
               tileSource:img2,
              shown: true
            }
          ],
          // OpenSeaDragon options
          osdOptions: {
            showNavigator:true,
            showNavigationControl: true
          },
        });

```
Please let me know how can I enable it. 

Thanks,
Zahra

**Comment by iangilman** [comment]
> I can also share the screenshot with you.

Please do, or a link to a working copy… Otherwise it's hard to visualize what you're referring to.

> I am trying to enable navigation control toolbar in Curtain sync as I am not using the separate Zoom buttons. But the toolbar is not showing up.

Yes, this is explicitly turned off in the code, overriding your options:

https://github.com/cuberis/openseadragon-curtain-sync/blob/04897720c5e166319ba0beaf47e78adaa45e2f38/src/openseadragon-curtain-sync.js#L391

You could comment that line out if you wanted to allow the regular OpenSeadragon buttons. Note that the curtain mode will have one set of buttons (since it's actually multiple images in a single viewer) and the sync mode will have one set of buttons per image (since each image is in its own viewer in that mode). That discrepancy is why we disabled that functionality; we decided it was nicer to have external buttons that would be consistent in both modes.

**Comment by zahranoorcs** [comment]
Ian,

Thanks a lot for quick response. Right now I am working locally. I will
soon upload it on server and then I can share link with u. It may take some
time as the images are pretty heavy. Meanwhile I am sharing the screenshot
with you if it can be of any help.

Thanks,
Zahra

**Comment by iangilman** [comment]
Sounds good!

I'm not seeing a screenshot, though… Did you attach it to your email reply? It's possible that doesn't work and you have to attach it directly in GitHub.

**Comment by zahranoorcs** [comment]
Ian,

Yes I did attach in email because somehow I was unable to do so in Github. My website is going to take time to upload. So, I replicated the issue in the Curtain-Sync code as I want to fix it asap. Please take a look and let me know if I am doing something wrong. 
Link to the issue : (https://zahranoorcs.github.io/OpenSeaDragon-CurtainSync/openseadragon-curtain-sync-masterTest/demo/index.html)
Link to the screenshot:[https://github.com/zahranoorcs/OpenSeaDragon-CurtainSync/blob/master/openseadragon-curtain-sync-masterTest/navigator.png](url)

Thanks

**Comment by zahranoorcs** [comment]
Ian,

You are awesome. It worked like a charm. Thanks alot for all your help and
support.
Yes, in the curtain mode, the image moves in the navigator which I thought
is intended behaviour. But for now, this bug doesn't bother me a lot. But
please keep me posted if it gets fixed in the near future.

Thanks again.

Best,
Zahra

**Comment by iangilman** [comment]
Excellent!

As for that bug, I've filed it as an issue here: https://github.com/openseadragon/openseadragon/issues/1831 You can follow it there if you want. We'll see if anyone picks it up, but at least now it's documented.

**Comment by zahranoorcs** [comment]
Ian,
Thanks a lot! 
Best,
Zahra
